#!/usr/bin/env python3

import hashlib

h = hashlib.md5()
h.update(input().encode("UTF-8"))
pw = ""
index = 0
pwl = 0
while pwl < 8:
    h2 = h.copy()
    h2.update(str(index).encode("UTF-8"))
    index += 1
    digest = h2.hexdigest()
    if digest[0:5] == "00000":
        print(digest[5], end="", flush=True)
        pwl += 1
print()
