#!/usr/bin/env python3

import sys

pixels = []
for row in range(6):
    pixels.append([False] * 50)

for line in sys.stdin:
    line = line.strip()
    if line.startswith("rect "):
        dim = tuple(int(s) for s in line[5:].split("x"))
        for col in range(dim[0]):
            for row in range(dim[1]):
                pixels[row][col] = True
    elif line.startswith("rotate column x="):
        col, dist = (int(s) for s in line[16:].split(" by "))
        old = [pixels[row][col] for row in range(6)]
        for row in range(6):
            pixels[(row + dist) % 6][col] = old[row]
    elif line.startswith("rotate row y="):
        row, dist = (int(s) for s in line[13:].split(" by "))
        newRow = [False] * 50
        for col in range(50):
            newRow[(col + dist) % 50] = pixels[row][col]
        pixels[row] = newRow
    else:
        raise RuntimeError("Unrecognized line")
print(sum(sum(elt for elt in row) for row in pixels))
