#!/usr/bin/env python3

import sys

count = 0
for line in sys.stdin:
    parts = [int(x) for x in line.strip().split()]
    parts.sort()
    if parts[0] + parts[1] > parts[2]:
        count += 1
print(count)
